name: isittofu
description: A tool for analyzing mobile OS codepoint coverage
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.0.1
  url_launcher: ^6.0.2

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - web/assets/images/
  fonts:
    - family: Poppins
      fonts:
        - asset: web/assets/fonts/Poppins-Black.otf
          weight: 900
        - asset: web/assets/fonts/Poppins-SemiBold.otf
          weight: 600
        - asset: web/assets/fonts/Poppins-Medium.otf
          weight: 500
