name: isittofu
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  provider: ^4.0.0
  url_launcher: ^5.4.1
  flutter_html: ^0.11.1
  bloom_filter:
#    path: ../bloom_filter
    git:
      url: https://github.com/amake/bloom_filter.git
      ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloom_filter_builder:
#    path: ../bloom_filter_builder
    git:
      url: https://github.com/amake/bloom_filter_builder.git
      ref: master

# Can't use builders with Flutter Web for now; see:
# https://github.com/flutter/flutter/issues/43639
#builders:
#  bloom_filter_builder:
##    path: ../bloom_filter_builder
#    git:
#      url: https://github.com/amake/bloom_filter_builder.git
#      ref: master

flutter:
  uses-material-design: true
