name: Flutter Web

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build Web
    env:
      my_secret: ${{secrets.commit_secret}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'beta'
          # Pin to 3.19.4 due to https://github.com/flutter/flutter/issues/145653
          flutter-version: '3.19.4'
      - run: flutter config --enable-web
      - run: flutter pub get
      - run: make test
      - run: make build-release
      - name: deploy
        run: |
          cd build/web
          echo tofu.quest > CNAME
          git init
          git config --global user.email aaron@madlon-kay.com
          git config --global user.name 'Aaron Madlon-Kay'
          git status
          git remote add origin https://${{secrets.commit_secret}}@github.com/amake/isittofu.git
          git checkout -b gh-pages
          git add --all
          git commit -m "CI update"
          git push origin gh-pages -f
